drop table MEMBER purge;

CREATE TABLE MEMBER(
	MEMBER_NAME VARCHAR2(20),
	MEMBER_ID VARCHAR2(20),
	MEMBER_PW VARCHAR2(20),
	MEMBER_PWCK VARCHAR2(20),
	MEMBER_EMAIL VARCHAR2(30),
	MEMBER_TEL VARCHAR2(30)
);

select * from MEMBER;

delete from MEMBER;

