drop table qna purge;

CREATE TABLE QNA(
	QNA_NUM NUMBER,
	QNA_NAME VARCHAR2(20),
	QNA_PASS VARCHAR2(15),
	QNA_SUBJECT VARCHAR2(50),
	QNA_CONTENT VARCHAR2(2000),
	QNA_RE_REF NUMBER,
	QNA_RE_LEV NUMBER,
	QNA_RE_SEQ NUMBER,
	QNA_READCOUNT NUMBER,
	QNA_DATE DATE,
	PRIMARY KEY(QNA_NUM)
);

select * from qna;

delete from qna;
